name: Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
        - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
 
